# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 64b0e2bb69b429d6f35ae16d5a248f7e879c4d8062ff9a0dca26090dc7c3801342fbd472e56dfc0b0279adb92bd3345ce449b7e3fe38127a6e55cb9c71ef61de

test:
  secret_key_base: 8e11d02109ed405cb9577a820216c37cd1a5deec8ac7d34194c33fae41ddb8d495862def00668a596020da3b126e534772f4b75592b075d998d4a1570f0e5048

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
